### ISSUE TITLE
The wormhole connector should support local development mode

### ISSUE THREAD

**Issue by lszymik** [kyma-incubator/wormhole#2]
There should be a possibility to start wormhole-connector on the local port without HTTPS.
Quite often, during the development on a local machine, we do not want to struggle with making CURL calls with an insecure flag or with additional `--proxy-cacert certs/ca.pem`.

There should be a start parameter indicating the `HTTP` or `HTTPS` mode.

**Comment by jcwiekala** [comment]
My team is working on integration between Kyma and Wordpress using wormhole-connector and wormhole-dispatcher. Unfortunately, it's a big problem to make requests with set something like curl's `--proxy-cacert` flag within Wordpress application on local environment. It would be much more easier if wormhole-connector could be started only using `HTTP` protocol instead of secured `HTTPS`, at least just for development purposes.
